/**:
  ros__parameters:
    obstacles/x: [1.0, -1.0, 0.0]
    obstacles/y: [0.0, 0.0, 1.0]
    obstacles/r: 0.038
    arena/x_length: 5.0
    arena/y_length: 7.0
    wall/thickness: 0.038
    rate: 100
    x0: 0.0
    y0: 0.0
    theta0: 0.0