/**:
  ros__parameters:
    wheel_radius: .033
    track_width: .16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 41.667
    encoder_ticks_per_rad: 651.899
    collision_radius: 0.11
    input_noise: 0.01
    basic_sensor_variance: 0.01
    slip_fraction: 0.001
    max_range: 0.7
    body_id: "blue/base_footprint"
    odom_id: "odom"
    wheel_left: "blue/wheel_left_joint"
    wheel_right: "blue/wheel_right_joint"